// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace NakuruTool_Avalonia_AOT.Features.AudioPlayer
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "nakuru_audio";





        /// <summary>
        ///  オーディオプレイヤーのインスタンスを作成
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern AudioPlayer* nakuru_audio_create();

        /// <summary>
        ///  オーディオプレイヤーのインスタンスを破棄
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_destroy(AudioPlayer* player);

        /// <summary>
        ///  状態変化コールバックを登録
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_set_state_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_set_state_callback(AudioPlayer* player, delegate* unmanaged[Cdecl]<NativeAudioPlayerState, void> callback);

        /// <summary>
        ///  オーディオファイルを再生
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_play", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int nakuru_audio_play(AudioPlayer* player, byte* file_path, int path_len);

        /// <summary>
        ///  再生を一時停止
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_pause", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_pause(AudioPlayer* player);

        /// <summary>
        ///  再生を再開
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_resume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_resume(AudioPlayer* player);

        /// <summary>
        ///  再生を停止
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_stop(AudioPlayer* player);

        /// <summary>
        ///  音量を設定 (0.0 - 1.0以上)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_set_volume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_set_volume(AudioPlayer* player, float volume);

        /// <summary>
        ///  現在の音量を取得 (0.0 - 1.0以上)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_get_volume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float nakuru_audio_get_volume(AudioPlayer* player);

        /// <summary>
        ///  現在の再生位置を取得 (秒単位)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_get_position", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double nakuru_audio_get_position(AudioPlayer* player);

        /// <summary>
        ///  現在の曲の総再生時間を取得 (秒単位)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_get_duration", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double nakuru_audio_get_duration(AudioPlayer* player);

        /// <summary>
        ///  指定した位置にシーク (秒単位)
        ///  ファイルを再オープンしてデコーダーに同期シークした新しいSinkに差し替える
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_seek", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_audio_seek(AudioPlayer* player, double position_secs);

        /// <summary>
        ///  現在の状態を取得
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_audio_get_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NativeAudioPlayerState nakuru_audio_get_state(AudioPlayer* player);


    }

    /// <summary>
    ///  オーディオプレイヤー
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AudioPlayer
    {
    }


    /// <summary>
    ///  オーディオプレイヤーの状態
    /// </summary>
    internal enum NativeAudioPlayerState : uint
    {
        Stopped = 0,
        Playing = 1,
        Paused = 2,
        Error = 3,
    }


}
