// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace NakuruTool_Avalonia_AOT.Features.BeatmapGenerator
{
    internal static unsafe partial class NativeStretchMethods
    {
        const string __DllName = "nakuru_stretch";





        /// <summary>
        ///  タイムストレッチ処理（ピッチ維持・速度変更）
        ///
        ///  seek() + process() + flush() 方式で固定長音声をストレッチする。
        ///
        ///  # 処理フロー
        ///  1. preset_default() で初期化、set_transpose_factor(1.0) でピッチ維持
        ///  2. seek() で先頭 input_latency 分をプリロール
        ///  3. process() ループ: 入力チャンク(playback_rate * BLOCK_FRAMES) → 出力チャンク(BLOCK_FRAMES)
        ///  4. 入力全消化後、末尾 input_latency 分のゼロ入力を追加で process()
        ///  5. flush() で残り output_latency 分を取得
        ///
        ///  # パラメータ
        ///  - `input_ptr`: インターリーブ f32 PCM入力
        ///  - `input_len`: 入力の総サンプル数（= frames * channels）
        ///  - `channels`: チャンネル数 (1 or 2)
        ///  - `sample_rate`: サンプリングレート
        ///  - `playback_rate`: 速度倍率 (&gt; 0.0, 例: 1.5 = 1.5倍速)
        ///
        ///  # 戻り値
        ///  成功時: data = Rust確保バッファ, len = 出力総サンプル数
        ///  失敗時: data = null, len = 0
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_stretch_process", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NakuruStretchResult nakuru_stretch_process(float* input_ptr, int input_len, int channels, int sample_rate, double playback_rate);

        /// <summary>
        ///  Rust側で確保したバッファを解放する。
        ///  nakuru_stretch_process の戻り値に対して必ず呼ぶこと。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "nakuru_stretch_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void nakuru_stretch_free(NakuruStretchResult result);


    }

    /// <summary>
    ///  Rust側で確保した出力バッファ。C#側で読み取り後、必ず nakuru_stretch_free で解放すること。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NakuruStretchResult
    {
        /// <summary>
        ///  出力データへのポインタ（インターリーブ f32）。エラー時は null。
        /// </summary>
        public float* data;
        /// <summary>
        ///  出力の総サンプル数（= frames * channels）。エラー時は 0。
        /// </summary>
        public int len;
    }



}
