// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace NakuruTool_Avalonia_AOT.Features.BeatmapGenerator
{
    internal static unsafe partial class NativeRateAudioMethods
    {
        const string __DllName = "nakuru_rate_audio";





        [DllImport(__DllName, EntryPoint = "nakuru_rate_audio_convert", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int nakuru_rate_audio_convert(byte* input_path, int input_path_len, byte* output_path, int output_path_len, double rate, int mode, int output_format, float quality, delegate* unmanaged[Cdecl]<float, void> progress_cb);

        [DllImport(__DllName, EntryPoint = "nakuru_rate_audio_get_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int nakuru_rate_audio_get_last_error(byte* buf, int buf_len);

        [DllImport(__DllName, EntryPoint = "nakuru_rate_audio_is_mp3_available", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int nakuru_rate_audio_is_mp3_available();


    }



}
